displayName=Bank Tags Extended
author=Emyrk
description=Extended bank tags with optional group sync for tags and Combat Achievements
tags=bank,banking,tag,tags,tab,tabs,layout,combat achievements,group ironman
version=${version}
plugins=com.emyrk.banktags.BankTagsPlugin,inventorysetups.InventorySetupsPlugin
build=standard
