displayName=Bank Tags Extended
author=Emyrk
description=A standalone replacement for RuneLite's built-in Bank Tags plugin
tags=bank,banking,tag,tags,tab,tabs,layout
version=
plugins=com.emyrk.banktags.BankTagsPlugin
build=standard
